services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3004:3004"
    volumes:
      - ./urls.json:/app/urls.json

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8098:80"
